-- ===========================================================================
-- Catálogo de materiales: el listado de obra, cargado de una vez
-- ===========================================================================
--
-- Viene de la planilla "Listado de materiales de obra - ordenado": rubro,
-- material y unidad. Es el catálogo común a todas las obras; lo que falte se
-- sigue cargando desde el gasto o desde la solapa Catálogo.
--
-- Los que ya estaban (ladrillos, bolsas, hierros, arena, granza, vigueta,
-- Sika Monotop, hidrófugo) no se tocan ni se repiten: conservan el nombre con
-- el que ya los usan los gastos. Por las dudas, un nombre que ya exista —aun
-- con otras mayúsculas— tampoco entra.
--
-- El rubro se busca en la plantilla (obra_id nulo) por nombre, sin mirar
-- mayúsculas. "Hormigón" de la planilla va a "Estructura de Hormigón Armado",
-- que es el rubro que existe. Las unidades de la planilla se llevan a las de
-- la app: m3 → m³, m2 → m², cajas → caja, gl → global.

insert into materiales (nombre, unidad, rubro_id)
select v.nombre, v.unidad, p.id
from (values
  ('Cantonera PVC', 'un', 'Albañilería'),
  ('Malla para revoque 5x5', 'rollo', 'Albañilería'),
  ('Pastina Prestige 2kg', 'un', 'Albañilería'),
  ('Pegamento ceramica Weber Basic 25kg', 'un', 'Revestimientos'),
  ('Pegamento porcellanato Weber Pro 25kg', 'un', 'Revestimientos'),
  ('Perfiles IPN Base tanque', 'un', 'Albañilería'),
  ('Piedra', 'kg', 'Albañilería'),
  ('Porcellanato Urban Concrete Tiza SL x 1.92m2', 'caja', 'Revestimientos'),
  ('Protex Latex 5kg', 'un', 'Albañilería'),
  ('Tacuru 20 lts', 'un', 'Albañilería'),
  ('Hormigon H21', 'm³', 'Estructura de Hormigón Armado'),
  ('Hormigon H21 bombeable', 'm³', 'Estructura de Hormigón Armado'),
  ('Instalación bomba', 'un', 'Estructura de Hormigón Armado'),
  ('Servicio bomba por m3', 'm³', 'Estructura de Hormigón Armado'),
  ('Aislante Aluminio doble 10mm x 20m', 'un', 'Cubiertas y Techos'),
  ('Alambre C9', 'kg', 'Estructura de Hormigón Armado'),
  ('Alambre C16', 'kg', 'Estructura de Hormigón Armado'),
  ('Alambre galvanizado C12', 'kg', 'Estructura de Hormigón Armado'),
  ('Chapa Acanalada C25', 'un', 'Cubiertas y Techos'),
  ('Chapa Traslucida Policarbonato', 'un', 'Cubiertas y Techos'),
  ('Hierro del 20', 'un', 'Estructura de Hormigón Armado'),
  ('Malla 15x15 4.2 mm de 6x2', 'un', 'Estructura de Hormigón Armado'),
  ('Malla sosten 10x10', 'm²', 'Cubiertas y Techos'),
  ('Perfil C 120 x 1.6mm x 4m', 'un', 'Cubiertas y Techos'),
  ('Perfil C 120 x 2.0mm x 4m', 'un', 'Cubiertas y Techos'),
  ('Tornillo para perfil C 2"', 'un', 'Cubiertas y Techos'),
  ('Cinta papel x 150 mts', 'un', 'Construcción en seco'),
  ('Fijacion N8 x 100 un', 'un', 'Construcción en seco'),
  ('Masilla x 32 kg', 'un', 'Construcción en seco'),
  ('Montante 34mm', 'un', 'Construcción en seco'),
  ('Placa de yeso estandar 12,5', 'un', 'Construcción en seco'),
  ('Solera 35mm', 'un', 'Construcción en seco'),
  ('Tornillos T1 x 100 un', 'un', 'Construcción en seco'),
  ('Tornillos T2 x 100 un', 'un', 'Construcción en seco'),
  ('Premarcos Carpintería Aluminio', 'global', 'Aberturas Ventanas'),
  ('Puertas entrada chapa 0,90 x 2,00', 'un', 'Aberturas Puertas'),
  ('Adaptador AW Aire 40 x 3/4', 'un', 'Instalación sanitaria'),
  ('Atrim desague cuadrado 10x10 AISI304', 'un', 'Artefactos y Griferías'),
  ('Bacha de apoyo Piazza A146', 'un', 'Artefactos y Griferías'),
  ('Bacha doble Mi Pileta ECO104', 'un', 'Artefactos y Griferías'),
  ('Base para tanque 1100 l', 'un', 'Instalación sanitaria'),
  ('Bomba Pluvius QB60 1/2 HP', 'un', 'Artefactos y Griferías'),
  ('Bomba Vasser Pre1', 'un', 'Artefactos y Griferías'),
  ('Boquilla Azul F 20', 'un', 'Instalación sanitaria'),
  ('Boquilla Azul F 25', 'un', 'Instalación sanitaria'),
  ('Boquilla Azul F 32', 'un', 'Instalación sanitaria'),
  ('Buje PP 1 1/2" a 1"', 'un', 'Instalación sanitaria'),
  ('Buje Red AW 110 x 63', 'un', 'Instalación sanitaria'),
  ('Buje Tigre Fusion Red 25 x 20', 'un', 'Instalación sanitaria'),
  ('Cañamo 20 grs', 'un', 'Instalación sanitaria'),
  ('Caño AW 40 x 0,25m', 'un', 'Instalación sanitaria'),
  ('Caño AW 40 x 0,50m', 'un', 'Instalación sanitaria'),
  ('Caño AW 40 x 1m', 'un', 'Instalación sanitaria'),
  ('Caño AW 40 x 2m', 'un', 'Instalación sanitaria'),
  ('Caño AW 40 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño AW 63 x 0,25m', 'un', 'Instalación sanitaria'),
  ('Caño AW 63 x 2m', 'un', 'Instalación sanitaria'),
  ('Caño AW 63 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño AW 110 x 0,25m', 'un', 'Instalación sanitaria'),
  ('Caño AW 110 x 1m', 'un', 'Instalación sanitaria'),
  ('Caño AW 110 x 2m', 'un', 'Instalación sanitaria'),
  ('Caño AW 110 x 3m', 'un', 'Instalación sanitaria'),
  ('Caño AW 110 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Cámara AW 110', 'un', 'Instalación sanitaria'),
  ('Caño Chapa 3" Redondo N30', 'un', 'Instalación sanitaria'),
  ('Caño IPS Fusion 25 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Sigas 20 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Sigas 25 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Sigas 32 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Tigre Fusion 20 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Tigre Fusion 25 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Tigre Fusion 32 x 4m', 'un', 'Instalación sanitaria'),
  ('Caño Tigre PVC Oring 110 x 1m', 'un', 'Instalación sanitaria'),
  ('Caño Tigre PVC Oring 110 x 4m', 'un', 'Instalación sanitaria'),
  ('Cinta perforada galvanizada x 10m', 'un', 'Instalación sanitaria'),
  ('Codo AW 45° 40 HH', 'un', 'Instalación sanitaria'),
  ('Codo AW 45° 40 MH', 'un', 'Instalación sanitaria'),
  ('Codo AW 45° 63 MH', 'un', 'Instalación sanitaria'),
  ('Codo AW 45° 110 MH', 'un', 'Instalación sanitaria'),
  ('Codo AW 90° 40 HH', 'un', 'Instalación sanitaria'),
  ('Codo AW 90° 40 MH', 'un', 'Instalación sanitaria'),
  ('Codo AW 90° 63 HH', 'un', 'Instalación sanitaria'),
  ('Codo AW 90° 63 MH', 'un', 'Instalación sanitaria'),
  ('Codo AW 90° 110 HH', 'un', 'Instalación sanitaria'),
  ('Codo AW 90° 110 MH', 'un', 'Instalación sanitaria'),
  ('Codo AW con 3 acometidas 110 x 63', 'un', 'Instalación sanitaria'),
  ('Codo Sigas 20 R/H 1/2"', 'un', 'Instalación sanitaria'),
  ('Codo Sigas 25 R/H 3/4"', 'un', 'Instalación sanitaria'),
  ('Codo Sigas 32 R/H 3/4"', 'un', 'Instalación sanitaria'),
  ('Codo Sigas 90° 20', 'un', 'Instalación sanitaria'),
  ('Codo Sigas 90° 25', 'un', 'Instalación sanitaria'),
  ('Codo Sigas 90° 32', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 20 c/inserto 1/2"', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 25 c/inserto 1/2"', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 45° 20', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 45° 25', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 45° 32', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 90° 20', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 90° 25', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion 90° 32', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion R/H 20 x 1/2"', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion R/H 25 x 3/4"', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion RH 20 x 1/2"', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion RH 25 x 3/4"', 'un', 'Instalación sanitaria'),
  ('Codo Tigre Fusion RM 20 x 1/2"', 'un', 'Instalación sanitaria'),
  ('Codo Tigre PVC Oring 45° 110 MH', 'un', 'Instalación sanitaria'),
  ('Codo Tigre PVC Oring 90° 110 MH', 'un', 'Instalación sanitaria'),
  ('Cupla Red PVC Tigre 100 x 63 MH', 'un', 'Instalación sanitaria'),
  ('Curva Chapa corrugada 45° 3"', 'un', 'Instalación sanitaria'),
  ('Embudo PVC Horizontal 110', 'un', 'Instalación sanitaria'),
  ('FV 106/I1 Ducha y Bañera Inox One', 'un', 'Artefactos y Griferías'),
  ('FV 181/I1 Lavatorio Mono Inox One', 'un', 'Artefactos y Griferías'),
  ('FV 189/I1 Bidet Mono Inox One', 'un', 'Artefactos y Griferías'),
  ('FV 411.04/I1 Cocina Mono Inox One', 'un', 'Artefactos y Griferías'),
  ('Gabinete Gas Fibrocemento 50x40', 'un', 'Instalación de Gas'),
  ('Llave Sigas 20', 'un', 'Instalación de Gas'),
  ('Llave Sigas 25', 'un', 'Instalación de Gas'),
  ('Llave Sigas 32', 'un', 'Instalación de Gas'),
  ('Llave Tigre Fusion 20', 'un', 'Instalación sanitaria'),
  ('Llave Tigre Fusion 25', 'un', 'Instalación sanitaria'),
  ('Pileta patio 20 x 20 3 salidas', 'un', 'Instalación sanitaria'),
  ('Pileta patio AW 3 x 40 c/sifon', 'un', 'Instalación sanitaria'),
  ('Pileta patio AW 7 x 40 c/sifon', 'un', 'Instalación sanitaria'),
  ('Portareja AW ciega inoxidable 15x15', 'un', 'Instalación sanitaria'),
  ('Ramal AW 45° 40 x 40', 'un', 'Instalación sanitaria'),
  ('Ramal AW 45° 110 x 63', 'un', 'Instalación sanitaria'),
  ('Ramal AW 45° 110 x 110', 'un', 'Instalación sanitaria'),
  ('Ramal Tigre PVC Oring 45° 110', 'un', 'Instalación sanitaria'),
  ('Red Sigas 25 x 20', 'un', 'Instalación de Gas'),
  ('Red Sigas 32 x 20', 'un', 'Instalación de Gas'),
  ('Red Sigas 32 x 25', 'un', 'Instalación de Gas'),
  ('Sellador H3 Verde x 125', 'un', 'Instalación sanitaria'),
  ('Silicona alta temperatura 280cc', 'un', 'Instalación sanitaria'),
  ('Sobrepaso Tigre Fusion 20', 'un', 'Instalación sanitaria'),
  ('Sobrepaso Tigre Fusion 25', 'un', 'Instalación sanitaria'),
  ('Solucion deslizante 440 cc', 'un', 'Instalación sanitaria'),
  ('Tanque Rotoplas 1100 l', 'un', 'Artefactos y Griferías'),
  ('Tapa AW 40 H', 'un', 'Instalación sanitaria'),
  ('Tapa AW 110 H', 'un', 'Instalación sanitaria'),
  ('Tapa PP RH 3/4"', 'un', 'Instalación sanitaria'),
  ('Tapa Sigas 20', 'un', 'Instalación de Gas'),
  ('Tapa Tigre Fusion 20', 'un', 'Instalación sanitaria'),
  ('Tapa Tigre Fusion 25', 'un', 'Instalación sanitaria'),
  ('Tapa Tigre Fusion 32', 'un', 'Instalación sanitaria'),
  ('Tapon PP 1/2"', 'un', 'Instalación sanitaria'),
  ('Tapon PP 3/4"', 'un', 'Instalación sanitaria'),
  ('Te Sigas 25', 'un', 'Instalación de Gas'),
  ('Te Sigas 25 x 20', 'un', 'Instalación de Gas'),
  ('Te Sigas 32', 'un', 'Instalación de Gas'),
  ('Te Sigas 32 x 25', 'un', 'Instalación de Gas'),
  ('Te Tigre Fusion 20', 'un', 'Instalación sanitaria'),
  ('Te Tigre Fusion 25', 'un', 'Instalación sanitaria'),
  ('Te Tigre Fusion 32', 'un', 'Instalación sanitaria'),
  ('Te Tigre Fusion R/H 20 x 1/2"', 'un', 'Instalación sanitaria'),
  ('Te Tigre Fusion Red 25 x 20', 'un', 'Instalación sanitaria'),
  ('Te Tigre Fusion Red 32 x 25', 'un', 'Instalación sanitaria'),
  ('Teflon 3/4" 20m', 'un', 'Instalación sanitaria'),
  ('Tornillo 8 + tarugo', 'un', 'Instalación sanitaria'),
  ('Tubo Tigre Fusion H 25 x 3/4"', 'un', 'Instalación sanitaria'),
  ('Tubo Tigre Fusion H 32 x 1"', 'un', 'Instalación sanitaria'),
  ('Tubo Tigre Fusion H 32 x 3/4"', 'un', 'Instalación sanitaria'),
  ('Tubo Tigre Fusion M 20 x 1/2"', 'un', 'Instalación sanitaria'),
  ('Tubo Tigre Fusion M 25 x 3/4"', 'un', 'Instalación sanitaria'),
  ('Tubo Tigre Fusion M 32 x 1"', 'un', 'Instalación sanitaria'),
  ('Tubo Tigre Fusion M 32 x 3/4"', 'un', 'Instalación sanitaria'),
  ('Union Doble Tigre Fusion 25', 'un', 'Instalación sanitaria'),
  ('Union Doble Tigre Fusion 32', 'un', 'Instalación sanitaria'),
  ('Union Sigas 20', 'un', 'Instalación de Gas'),
  ('Union Sigas 25', 'un', 'Instalación de Gas'),
  ('Union Sigas 32', 'un', 'Instalación de Gas'),
  ('Union Tigre Fusion 20', 'un', 'Instalación sanitaria'),
  ('Union Tigre Fusion 25', 'un', 'Instalación sanitaria'),
  ('Union Tigre Fusion 32', 'un', 'Instalación sanitaria'),
  ('Valvula Esférica Valforte 1" H-H', 'un', 'Instalación sanitaria'),
  ('Valvula Esférica Valforte 3/4" H-H', 'un', 'Instalación sanitaria'),
  ('Valvula Retención Valforte 1"', 'un', 'Instalación sanitaria'),
  ('Ventilacion TBU p/ calefactor 2000/3000', 'un', 'Instalación sanitaria'),
  ('Caja de inspección jabalina', 'un', 'Instalación eléctrica'),
  ('Caja medidor monofásica', 'un', 'Instalación eléctrica'),
  ('Caja mignon', 'un', 'Instalación eléctrica'),
  ('Caja octogonal', 'un', 'Instalación eléctrica'),
  ('Caja rectangular', 'un', 'Instalación eléctrica'),
  ('Caja registro 15x15', 'un', 'Instalación eléctrica'),
  ('Caño corrugado 1 1/4"', 'un', 'Instalación eléctrica'),
  ('Caño corrugado 1"', 'un', 'Instalación eléctrica'),
  ('Caño corrugado 7/8"', 'un', 'Instalación eléctrica'),
  ('Caño pilar 1 1/4"', 'un', 'Instalación eléctrica'),
  ('Conector hierro 7/8"', 'un', 'Instalación eléctrica'),
  ('Curva para pilar 1 1/4"', 'un', 'Instalación eléctrica'),
  ('Jabalina', 'un', 'Instalación eléctrica'),
  ('Tablero 4 modulos embutir', 'un', 'Instalación eléctrica'),
  ('Tablero 24 modulos embutir', 'un', 'Instalación eléctrica')
) as v(nombre, unidad, rubro)
left join rubros p on p.obra_id is null and lower(p.nombre) = lower(v.rubro)
where not exists (
  select 1 from materiales m where lower(btrim(m.nombre)) = lower(btrim(v.nombre))
)
on conflict (nombre) do nothing;
